# Generated by Django 5.2.4 on 2025-07-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclassifications',
            name='confidence',
            field=models.FloatField(default=0),
        ),
    ]
