# Generated by Django 5.2.4 on 2025-08-05 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0002_userclassifications_confidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='userclassifications',
            name='info',
            field=models.TextField(default='N/A'),
        ),
        migrations.AddField(
            model_name='userclassifications',
            name='model',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
