# Generated by Django 5.2.4 on 2025-08-15 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classifier', '0003_userclassifications_info_userclassifications_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserShares',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('linked_record_id', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
